export const ROUTES_NAME = {
  AUTH: {
    LOGIN: '/login',
    SEND_CODE: '/send-code',
    CHECK_CODE: '/check-code',
    REGISTER: '/register',
    REST_PASSWORD: '/rest-password',
    UPDATE_PASSWORD: '/update-password',
    VERIFY_USER: '/verify-user',
    VERIFY_CODE: '/verify-code',
    AUTHENTICATE: '/authenticate',
    LOGIN_PHONE: '/login-phone',
    VERIFY_TOKEN: '/verify-token',
    REFRESH_TOKEN: '/refresh-token',
    USER: '/getMe',
    GET_ALL_USERS: '/get-all-users',
    CHECK_PHONE: '/check-phone',
    LOGOUT: '/logout',
  },

  USER: {
    ADD_USER: '/add-user',
    UPDATE_USER: '/update-user-w1',
  },
  PRODUCT: {
    GET_ALL_PRODUCTS: '/get-all',
    GET_PRODUCT_BY_NAME_OR_CODE: '/get',
    GET_ALL_PRODUCT_SHOP: '/get-all-shop',
    GET_ALL_PRODUCT_TOP: '/get-all-top',
    GET_ALL_PRODUCT_PAY_TOP: '/get-all-pay-top',
    GET_ALL_PRODUCT_NEW_SHOP: '/get-all-new-shop',
  },
  COMMENT: {
    ADD_NEW_COMMENT: '/add-comment',
    GET_COMMENT: '/get-comment',
  },
  SEARCH: {
    SEARCH: '/search',
    LIST_TEXT_SEARCH: '/text-search-product',
    LIST_SHOP_NAME_OR_CODE: '/shop-by-name-or-code',
  },
  CART: {
    GET_CART: '/get-cart',
    ADD_CART: '/add-cart',
    REMOVE_CART: '/remove-cart',
    REMOVE_CART_BY_CODE: '/remove-cart-by-code-product',
  },
  ORDER: {
    HOME: '/order',
    GET_ORDER_DETAIL_BY_CODE: '/get-order',
    GET_ORDER_BY_USER: '/get-order-user',
    GET_ORDER_BY_ALL_ADMIN: '/get-order-all',
    CONFIRM_ORDER_SUCCESS: '/confirm-order-success',
  },
  ADDRESS: {
    HOME: '/address',
    GET_ADDRESS: '/get-address',
    ADD_ADDRESS: '/add-address',
    DETAIL_ADDRESS: '/detail-address',
    UPDATE_ADDRESS_USER_BY_CODE: '/update-address-user-by-code',
    REMOVE_ADDRESS_USER_BY_CODE: '/remove-address-user-by-code',
  },
  CHECKOUT: '/checkout',
  PAYMENT: {
    HOME: '/payment',
    GET_ALL_PAYMENT: '/get-all-pay-ment',
  },
  NOTIFICATION: {
    HOME: '/notification',
    CHECKOUT: '/checkout',
  },
  SHOP: {
    HOME: '/shop',
    DETAIL_SHOP: '/detail-shop',
    PRODUCT_SHOP: '/all-product',
    FOLLOW_SHOP: '/follow-shop',
    DISABLE_FOLLOW_SHOP: '/disable-follow-shop',
    CATEGORY_SHOP: '/all-category-shop',
  },
  NOTIFY: {
    HOME: '/notify',
    ADD_NOTIFY_NEW_SHOP: '/add-new-notify-shop',
    GET_ALL_NOTIFY_USER: '/get-all-notify-user',
  },
  CHAT: {
    HOME: '/messenger',
    SEND_CHAT: '/send-messenger',
    GET_ALL_CHAT: '/get-all-messenger',
  },
  EVALUATE: {
    HOME: '/evaluate',
    ADD_EVALUATE: '/add',
    REMOVE_EVALUATE: '/remove',
    GET_ALL_EVALUATE: '/get-all',
    CHECK_EVALUATE: '/check-evaluate',
    GET_EVALUATE: '/get-evaluate',
  },
  VOUCHER: {
    HOME: '/voucher',
    CHECK_VOUCHER: '/check-voucher',
  },
};

export const ROUTES_NAME_SHOP = {
  AUTH: {
    LOGIN: '/login',
    GET_ME: '/getMe',
    GET_ME_SHOP: '/getMeShop',
    REGISTER: '/register',
    VERIFICATION_ACCOUNT: '/verification-active',
    UPDATE_USER: '/update-user',
    LOGOUT: '/logout',
    CHECK_PASSWORD: '/check-password',
    REMOVE_SHOP: '/remove-shop',
    LOGIN_SECURITY: '/security-login',
    REST_PASSWORD: '/rest-pass',
    CONFIRM_REST_PASSWORD: '/confirm-rest-password',
  },
  GET_INDEX_DATA: {
    DATA: '/get-data',
  },
  VERIFICATION: {
    HOME: '/verification',
    GET_VERIFICATION: '/get-code-verification',
  },
  CATEGORY: {
    HOME: '/category',
    CATEGORY_BY_PRODUCT_SHOP: '/get-by-product-shop',
    CATEGORY_ALL_BY_SHOP: '/get-all-category-by-shop',
    ADD_NEW_CATEGORY: '/add-new-category',
    REMOVE_CATEGORY: '/remove-category',
    UPDATE_CATEGORY: '/update-category',
  },
  PRODUCT: {
    HOME: '/product',
    ADD_PRODUCT: '/add-product',
    GET_PRODUCT_BY_CODE: '/get-product-by-code-and-shop',
    GET_ALL_PRODUCT: '/get-all-product',
    GET_ALL_TYPE_PRODUCT: '/get-all-type-product',
    ADD_TYPE_PRODUCT: '/add-type-product',
    REMOVE_PRODUCT_BY_SHOP: '/remove-product-by-shop',
    SEARCH_PRODUCT_BY_VALUE_AND_SHOP: '/searc-product-by-value-and-shop',
    UPDATE_PRODUCT_PRODUCT_BY_CODE_AND_SHOP: '/update-product-by-code-and-shop',
  },
  UPLOAD: {
    home: '/upload',
    image: '/image',
    images: '/images',
    video: '/video',
    videos: 'videos',
  },
  ORDER: {
    HOME: '/order',
    ADD_ORDER_BY_SHOP: '/add-order-by-shop',
    HIDE_ORDER_BY_SHOP: '/hide-order-by-shop',
    REMOVE_ORDER_BY_SHOP: '/remove-order-by-shop',
    GET_ALL_ORDER_BY_SHOP: '/get-all-order-by-shop',
    GET_ALL_PRODUCT_BY_ORDER_AND_SHOP: '/get-all-product-by-order-and-shop',
    GET_ORDER_DETAIL_BY_ORDER_AND_SHOP: '/get-order-detail-by-order-and-shop',
    CONFIRM_ORDER_BY_CODE_ORDER: '/confirm-order-by-code-order',
  },
  NOTIFY: {
    HOME: '/notify',
    GET_ALL_NOTIFY_SHOP: '/get-all-notify-shop',
    GET_DETAIL_NOTIFY: '/notify-detail',
    ADD_NEW_NOTIFY_USER: '/add-new-notify-user',
  },
  CHAT: {
    HOME: '/messenger',
    SEND_CHAT: '/send-messenger',
    GET_ALL_CHAT: '/get-all-messenger',
    GET_ALL_USER_CHAT_BY_SHOP: '/get-all-user-messenger-by-shop',
  },
  VOUCHER: {
    HOME: '/voucher',
    GET_ALL_VOUCHER: '/get-all-voucher',
    GET_DETAIL_VOUCHER: '/get-detail-voucher',
    ADD_NEW_VOUCHER: '/add-new-voucher',
    UPDATE_VOUCHER: '/update-voucher',
    REMOVE_VOUCHER: '/remove-voucher',
  },
  STATISTICAL: {
    HOME: '/statistical',
    GET_STATISTICAL: '/get-statistical',
    GET_STATISTICAL_FULL: '/get-statistical-full',
  },
  SETTING: {
    HOME: '/setting',
    GET_SETTING: '/get-setting-by-shop',
    UPDATE_SETTING: '/update-setting-by-shop',
  },
  FOLLOW: {
    HOME: '/follow',
    GET_USER_FOLLOW_BY_SHOP: '/get-all-user-follow-by-shop',
  },
};
export const SOCKET_ROUTE = {
  NOTIFICATION: {
    HOME: '/notification',
    SEND: '/send',
  },
};
